Refactor cell params hierarchy
MetaCell/geppetto-netpyne pull request #82
Opened 2018-11-04 13:41 UTC by rodriguez-facundo

refactor cellParams navigation according to mockup and feedback from sprint.

I also added some refactoring to make the code more readable.

travis might not pass because development has been updated with appbar PR. I will work on travis on Tuesday

2018-11-12 23:57 UTC, rodriguez-facundo commented
I think it is ready now. The gear button was inside sections, so I removed and relaunched Travis

2018-11-20 21:20 UTC, adrianq requested changes
@rodriguez-facundo  User experience is much better and the graphical interfaces looks really nice. Tests are passing as well. I have dropped a few comments regarding the code. Hopefully they are not too painful and will help to read and maintain the code in the future. Please have a look at them and let me know if you want to discuss anything. Thanks!

2018-11-20 21:20 UTC, adrianq commented on components/definition/cellRules/NetPyNECellRules.js
> +              data-tooltip={
Can we change this to a classic if/else? Probably you can even extract it to a method and maybe reuse in several places?

2018-11-20 21:20 UTC, adrianq commented on components/definition/cellRules/NetPyNECellRules.js
> +              { page != 'main'
Can we change this to a classic if/else? Probably you can even extract it to a method and maybe reuse in several places?

2018-11-20 21:20 UTC, adrianq commented on components/definition/cellRules/NetPyNECellRules.js
> +              data-tooltip={ page == 'mechanisms'
Can we change this to a classic if/else? Probably you can even extract it to a method and maybe reuse in several places? Too difficult to understand what is going on

2018-11-20 21:20 UTC, adrianq commented on components/definition/cellRules/NetPyNECellRules.js
> +                  ? selectedSection != undefined
Can we change this to a classic if/else? Probably you can even extract it to a method and maybe reuse in several places?

2018-11-20 21:20 UTC, adrianq commented on components/definition/cellRules/NetPyNECellRules.js
> +          { page == "main" ? cellRulesContainer : page == "sections" ? sectionsContainer : mechanismsContainer }
Can we change this to a classic if/else? Probably you can even extract it to a method and maybe reuse in several places?

2018-11-20 21:20 UTC, adrianq commented on components/definition/cellRules/sections/NetPyNESectionThumbnail.js
> +        {(isHovered && selected)
Can we change this to a classic if/else? Probably you can even extract it to a method and maybe reuse in several places?

2018-11-20 21:20 UTC, adrianq commented on components/definition/cellRules/sections/mechanisms/NetPyNEMechanismThumbnail.js
> +            {(isHovered && selected)
Can we change this to a classic if/else? Probably you can even extract it to a method and maybe reuse in several places?

2018-11-20 21:20 UTC, adrianq commented on components/definition/cellRules/sections/mechanisms/NetPyNENewMechanism.js
> +  async componentDidMount() {
No need for this async/await. Just do a regular `evalPythonMessage.then`

2018-11-20 21:20 UTC, adrianq commented on components/definition/cellRules/sections/mechanisms/NetPyNENewMechanism.js
> +        {disabled
Can we change this to a classic if/else? Probably you can even extract it to a method and maybe reuse in several places?

2018-11-20 21:20 UTC, adrianq commented on components/general/CustomIcons.js
> +const HomeIcon = (props) => (
Remove this CustomIcons class. I know this icon is being used in two different files but I don't think it is a good idea to start a CustomIcons for now

2018-11-20 21:20 UTC, adrianq commented on components/general/CustomIcons.js
> +const HomeIcon = (props) => (
Btw why don't we use a regular material ui icon? See https://material.io/tools/icons/?icon=home&style=baseline

2018-11-20 21:20 UTC, adrianq commented on components/general/NetPyNEThumbnail.js
> +            {isHovered && selected ? "" : name.length > 14 ? name.slice(0,11)+"...": name}
Can we use a regular if/else?

2018-11-20 21:20 UTC, adrianq commented on components/definition/cellRules/NetPyNECellRules.js
> +    const { page, selectedCellRule, value } = this.state;
I am bit scared of this method. Can we simplify it somehow? Maybe change the swithc with a if/else and double check if we can simplify some conditions or merge two of them... Some comments will be helpful when we look at this code in a few weeks as well

2018-11-21 19:14 UTC, adrianq approved these changes

2018-11-21 19:14 UTC, merged